"""Repository port for sales-playbook application services."""

from __future__ import annotations

from typing import Protocol

from power_web_os.application.sales_playbook.contracts import (
    ProductLifecycle,
    ProductSummary,
    SalesPlaybookDefinitionVersion,
    SalesPlaybookDraft,
)


class DraftConflictError(RuntimeError):
    pass


class ProductNotFoundError(LookupError):
    pass


class SalesPlaybookRepository(Protocol):
    def create_product(self, draft: SalesPlaybookDraft) -> ProductSummary: ...
    def list_products(self) -> tuple[ProductSummary, ...]: ...
    def get_product(self, product_id: str) -> ProductSummary | None: ...
    def get_draft(self, product_id: str) -> SalesPlaybookDraft | None: ...
    def save_draft(self, draft: SalesPlaybookDraft, *, expected_revision: int) -> SalesPlaybookDraft: ...
    def publish(self, draft: SalesPlaybookDraft, *, published_by: str, activate: bool) -> SalesPlaybookDefinitionVersion: ...
    def list_versions(self, product_id: str) -> tuple[SalesPlaybookDefinitionVersion, ...]: ...
    def get_version(self, product_id: str, version_id: str) -> SalesPlaybookDefinitionVersion | None: ...
    def activate(self, product_id: str, version_id: str) -> SalesPlaybookDefinitionVersion: ...
    def replace_draft(self, draft: SalesPlaybookDraft) -> SalesPlaybookDraft: ...
    def set_lifecycle(self, product_id: str, lifecycle: ProductLifecycle) -> ProductSummary: ...
