"""Repository port for roadmap slice storage."""

from __future__ import annotations

from typing import Protocol

from power_web_os.roadmap.models import RoadmapSlice, SliceEvent, SliceLink


class RoadmapRepository(Protocol):
    def initialize(self) -> None: ...

    def upsert_slice(self, roadmap_slice: RoadmapSlice) -> None: ...

    def get_slice(self, slice_id: str) -> RoadmapSlice | None: ...

    def list_slices(self, *, status: str | None = None, track: str | None = None) -> list[RoadmapSlice]: ...

    def update_status(self, slice_id: str, status: str, *, note: str | None = None) -> None: ...

    def add_event(self, event: SliceEvent) -> None: ...

    def add_link(self, link: SliceLink) -> None: ...

    def set_meta(self, key: str, value: str) -> None: ...

    def get_meta(self, key: str, default: str = "") -> str: ...

