import { AlertTriangle, CheckCircle2, ChevronDown, GitBranch, Lightbulb, Route, ShieldCheck, Target } from 'lucide-react';
import type { ReactNode } from 'react';
import { useState } from 'react';
import { Badge, Button, Card, Eyebrow, Mono } from '../components/primitives';
import type { AccessPlanArtifact, Evidence, Route as AccessRoute, Signal } from '../types';

export function AccessPlansScreen({
  artifact,
  error,
}: {
  artifact: AccessPlanArtifact | null;
  error: string | null;
}) {
  const [openRouteType, setOpenRouteType] = useState<string | null>(null);

  if (error) {
    return (
      <StatusPanel title="Artifact is not ready" eyebrow="DEMO STATUS">
        <p>Run the access plan generator, then restart or refresh the local demo server.</p>
        <code>python -m power_web_os.demo generate-access-plan</code>
      </StatusPanel>
    );
  }

  if (!artifact) {
    return (
      <StatusPanel title="Loading Access Plan" eyebrow="DEMO STATUS">
        <p>Reading the generated artifact from the local Vite server.</p>
      </StatusPanel>
    );
  }

  const routes = artifact.access_plan.routes;
  const activeRouteType = openRouteType ?? routes[0]?.route_type;

  return (
    <section className="screen access-plans-screen" aria-label="Access Plans">
      <div className="objective-banner">
        <div className="objective-icon">
          <Target aria-hidden="true" />
        </div>
        <div className="objective-copy">
          <Eyebrow>Objective</Eyebrow>
          <h1>Reach the buying committee through a trusted, in-policy route</h1>
          <p>
            {artifact.account.name} has {artifact.access_plan.unresolved_gaps.length} unresolved power figures and{' '}
            {routes.length} ranked access routes generated by {artifact.workflow_metadata.workflow_name}.
          </p>
        </div>
        <Badge tone="cobalt">{artifact.workflow_metadata.runtime}</Badge>
      </div>

      <div className="plans-layout">
        <div className="plans-main">
          <div className="route-list">
            {routes.map((route, index) => (
              <PlanCard
                key={route.route_type}
                artifact={artifact}
                index={index}
                open={route.route_type === activeRouteType}
                route={route}
                onToggle={() => setOpenRouteType(route.route_type === activeRouteType ? null : route.route_type)}
              />
            ))}
          </div>
        </div>

        <aside className="plans-inspector">
          <BoardSummary artifact={artifact} />
          <EvidenceSummary signals={artifact.account.signals} />
        </aside>
      </div>
    </section>
  );
}

function PlanCard({
  artifact,
  index,
  open,
  route,
  onToggle,
}: {
  artifact: AccessPlanArtifact;
  index: number;
  open: boolean;
  route: AccessRoute;
  onToggle: () => void;
}) {
  const evidence = evidenceForRoute(artifact.account.signals, route.evidence_refs);

  return (
    <Card interactive selected={index === 0} onClick={onToggle}>
      <div className="plan-card-header">
        <div className="rank-block">
          <span className="rank-label">RANK</span>
          <span className="rank-value">{index + 1}</span>
        </div>
        <div className="plan-heading">
          <div className="plan-title-row">
            <h2>{route.title}</h2>
            {index === 0 && <Badge tone="cobalt">Recommended</Badge>}
          </div>
          <p>Target / {humanize(route.route_type)}</p>
        </div>
        <div className="score-block">
          <span className="rank-label">SCORE</span>
          <span className="score-row">
            <span className="score-track">
              <span className="score-fill" style={{ width: `${route.score}%` }} />
            </span>
            <Mono>{route.score}</Mono>
          </span>
        </div>
        <ChevronDown aria-hidden="true" className={`chevron${open ? ' chevron-open' : ''}`} />
      </div>

      {open && (
        <div className="plan-card-detail">
          <div className="route-explanation">
            <Eyebrow>Route</Eyebrow>
            <div className="route-path">
              <span>{route.owner}</span>
              <Route aria-hidden="true" />
              <span>{route.title}</span>
            </div>

            <div className="why-box">
              <Lightbulb aria-hidden="true" />
              <div>
                <span className="why-title">Why this route</span>
                <p>{route.reason}</p>
              </div>
            </div>

            <Eyebrow>Expected state change</Eyebrow>
            <div className="state-change">
              <GitBranch aria-hidden="true" />
              <span>{route.expected_state_change}</span>
            </div>

            <p className="risk-line">
              <AlertTriangle aria-hidden="true" />
              <span>{route.risk}</span>
            </p>
          </div>

          <div className="route-meta">
            <div className="hook-card">
              <Eyebrow>Review status</Eyebrow>
              <h3>{route.requires_human_review ? 'Human approval required' : 'Ready for tasking'}</h3>
              <p>Playbook rule <Mono>required_review_for: all</Mono> keeps this route review-first.</p>
            </div>

            <div>
              <Eyebrow>Evidence</Eyebrow>
              <div className="evidence-list">
                {evidence.map((item) => (
                  <span className="evidence-item" key={item.source}>
                    <CheckCircle2 aria-hidden="true" />
                    <span>{item.summary}</span>
                    <Mono>{item.source}</Mono>
                  </span>
                ))}
              </div>
            </div>

            <div className="metadata-row">
              <Badge tone="neutral">{route.owner}</Badge>
              <Badge tone={route.requires_human_review ? 'unsurfaced' : 'ally'}>
                {route.requires_human_review ? 'Review required' : 'Ready'}
              </Badge>
            </div>
          </div>
        </div>
      )}
    </Card>
  );
}

function BoardSummary({ artifact }: { artifact: AccessPlanArtifact }) {
  return (
    <Card>
      <div className="inspector-section">
        <Eyebrow>Board coverage</Eyebrow>
        <div className="coverage-number">
          <span>{artifact.account.roles.length}</span>
          <span>/{artifact.account.roles.length + artifact.access_plan.unresolved_gaps.length}</span>
        </div>
        <p className="muted">Visible and missing power figures from the current synthetic account artifact.</p>
        <div className="badge-list">
          {artifact.account.roles.map((role) => (
            <Badge key={role.role} tone={role.relation === 'partner' ? 'cobalt' : 'ally'}>
              {role.person_name ?? role.role}
            </Badge>
          ))}
          {artifact.access_plan.unresolved_gaps.map((gap) => (
            <Badge key={gap} tone="unsurfaced">
              {humanize(gap)}
            </Badge>
          ))}
        </div>
      </div>
    </Card>
  );
}

function EvidenceSummary({ signals }: { signals: Signal[] }) {
  return (
    <Card>
      <div className="inspector-section">
        <Eyebrow>Signal evidence</Eyebrow>
        <div className="signal-stack">
          {signals.map((signal) => (
            <div className="signal-row" key={signal.kind}>
              <ShieldCheck aria-hidden="true" />
              <div>
                <h3>{signal.kind}</h3>
                <p>{signal.summary}</p>
                <Mono>{score(signal.strength)} strength</Mono>
              </div>
            </div>
          ))}
        </div>
      </div>
    </Card>
  );
}

function StatusPanel({
  children,
  eyebrow,
  title,
}: {
  children: ReactNode;
  eyebrow: string;
  title: string;
}) {
  return (
    <section className="screen status-screen">
      <Card>
        <Eyebrow>{eyebrow}</Eyebrow>
        <h1>{title}</h1>
        {children}
      </Card>
    </section>
  );
}

function evidenceForRoute(signals: Signal[], refs: string[]): Evidence[] {
  const evidence = signals.flatMap((signal) => signal.evidence);
  return evidence.filter((item) => refs.includes(item.source));
}

function score(value: number) {
  return String(Math.round(value * 100));
}

function humanize(value: string) {
  return value.replaceAll('_', ' ');
}
