import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

export const supportedLocales = ['en', 'ru'] as const;
export type SupportedLocale = (typeof supportedLocales)[number];

export const defaultLocale: SupportedLocale = 'en';
export const localeStorageKey = 'power-web-os-locale';

export const resources = {
  en: {
    translation: {
      app: {
        brandMeta: 'Access workspace',
        workflowBadge: 'Access loop',
      },
      nav: {
        workspace: 'Workspace',
        queue: 'Queue',
        accounts: 'Accounts',
        map: 'Account Map',
        plans: 'Access Plans',
        signals: 'Signals',
        playbook: 'Playbook',
        tasks: 'My Tasks',
        inbox: 'Signals Inbox',
      },
      topbar: {
        routeCount: '{{count}} ranked routes',
        fallbackMeta: 'Generated Access Plan artifact',
        searchLabel: 'Search accounts and people',
        searchPlaceholder: 'Search accounts, people',
        filters: 'Filters',
        notifications: 'Notifications',
        addAccount: 'Add account',
        language: 'Language',
        accessPlansFor: 'Access Plans / {{accountName}}',
        icpFitHealth: 'ICP fit health',
      },
      accounts: {
        aria: 'Accounts portfolio',
        eyebrow: 'Account Radar',
        title: 'Accounts',
        summary:
          '{{count}} target accounts ranked by ICP fit, signal strength, access route, and missing-role risk.',
        topAccount: 'Top account',
        radarScoreValue: '{{score}} radar score',
        filters: {
          aria: 'Portfolio filters',
          all: 'All accounts',
          myBook: 'My book',
          needsRoute: 'Needs route',
          reviewRequired: 'Review required',
        },
        columns: {
          account: 'Account',
          stage: 'Stage',
          radarScore: 'Radar score',
          signals: 'Signals',
          missing: 'Missing',
          bestRoute: 'Best route',
          owner: 'Owner',
          review: 'Review',
        },
        noRoute: 'No route yet',
        unassigned: 'Unassigned',
        ready: 'Ready',
        reviewRequired: 'Review required',
        scoreLabel: '{{accountName}} radar score',
        status: {
          eyebrow: 'RADAR STATUS',
          notReadyTitle: 'Account Radar is not ready',
          notReadyCopy: 'Run the portfolio generator, then restart or refresh the local demo server.',
          loadingTitle: 'Loading Account Radar',
          loadingCopy: 'Reading the generated portfolio artifact from the local Vite server.',
        },
      },
      plans: {
        aria: 'Access Plans',
        statusEyebrow: 'DEMO STATUS',
        artifactNotReadyTitle: 'Artifact is not ready',
        artifactNotReadyCopy: 'Run the access plan generator, then restart or refresh the local demo server.',
        loadingTitle: 'Loading Access Plan',
        loadingCopy: 'Reading the generated artifact from the local Vite server.',
        objectiveEyebrow: 'Objective',
        objectiveTitle: 'Reach the buying committee through a trusted, in-policy route',
        objectiveCopy:
          '{{accountName}} has {{gapCount}} unresolved power figures and {{routeCount}} ranked access routes generated by {{workflowName}}.',
        rank: 'RANK',
        score: 'SCORE',
        recommended: 'Recommended',
        target: 'Target / {{target}}',
        routeEyebrow: 'Route',
        whyThisRoute: 'Why this route',
        expectedStateChange: 'Expected state change',
        reviewStatus: 'Review status',
        humanApprovalRequired: 'Human approval required',
        readyForTasking: 'Ready for tasking',
        reviewRule: 'Playbook rule',
        reviewRuleCopy: 'keeps this route review-first.',
        evidence: 'Evidence',
        boardCoverage: 'Board coverage',
        boardCoverageCopy: 'Visible and missing power figures from the current synthetic account artifact.',
        signalEvidence: 'Signal evidence',
        strength: '{{score}} strength',
      },
      planned: {
        workspaceEyebrow: 'PLANNED WORKSPACE',
        queueEyebrow: 'PLANNED QUEUE',
        map: {
          title: 'Account Map',
          description: 'The Power Web map will show visible and missing buying-committee figures around the account.',
          nextSlice: 'Slice 0.5',
        },
        signals: {
          title: 'Signals',
          description: 'The signals feed will expose source evidence, recency, confidence, and governance warnings.',
          nextSlice: 'Slice 0.11',
        },
        playbook: {
          title: 'Playbook',
          description: 'The playbook workspace will show allowed routes, blocked channels, assets, and review rules.',
          nextSlice: 'Slice 0.6',
        },
        tasks: {
          title: 'My Tasks',
          description: 'Approved routes will become task candidates after the human-review loop is implemented.',
          nextSlice: 'Slice 0.7',
        },
        inbox: {
          title: 'Signals Inbox',
          description: 'New signals will be triaged here once the radar and source-governance loops exist.',
          nextSlice: 'Slice 0.10',
        },
      },
    },
  },
  ru: {
    translation: {
      app: {
        brandMeta: 'Рабочее пространство доступа',
        workflowBadge: 'Контур доступа',
      },
      nav: {
        workspace: 'Рабочая область',
        queue: 'Очередь',
        accounts: 'Аккаунты',
        map: 'Карта аккаунта',
        plans: 'Планы доступа',
        signals: 'Сигналы',
        playbook: 'Плейбук',
        tasks: 'Мои задачи',
        inbox: 'Входящие сигналы',
      },
      topbar: {
        routeCount: '{{count}} маршрута доступа',
        fallbackMeta: 'Сгенерированный артефакт плана доступа',
        searchLabel: 'Поиск аккаунтов и людей',
        searchPlaceholder: 'Поиск аккаунтов, людей',
        filters: 'Фильтры',
        notifications: 'Уведомления',
        addAccount: 'Добавить аккаунт',
        language: 'Язык',
        accessPlansFor: 'Планы доступа / {{accountName}}',
        icpFitHealth: 'Соответствие ICP',
      },
      accounts: {
        aria: 'Портфель аккаунтов',
        eyebrow: 'Радар аккаунтов',
        title: 'Аккаунты',
        summary:
          '{{count}} целевых аккаунтов ранжированы по ICP, силе сигналов, маршруту доступа и риску недостающих ролей.',
        topAccount: 'Топ аккаунт',
        radarScoreValue: '{{score}} радар-скор',
        filters: {
          aria: 'Фильтры портфеля',
          all: 'Все аккаунты',
          myBook: 'Мой портфель',
          needsRoute: 'Нужен маршрут',
          reviewRequired: 'Нужна проверка',
        },
        columns: {
          account: 'Аккаунт',
          stage: 'Этап',
          radarScore: 'Радар-скор',
          signals: 'Сигналы',
          missing: 'Пробелы',
          bestRoute: 'Лучший маршрут',
          owner: 'Владелец',
          review: 'Проверка',
        },
        noRoute: 'Маршрута пока нет',
        unassigned: 'Не назначен',
        ready: 'Готово',
        reviewRequired: 'Нужна проверка',
        scoreLabel: 'Радар-скор {{accountName}}',
        status: {
          eyebrow: 'СТАТУС РАДАРА',
          notReadyTitle: 'Радар аккаунтов не готов',
          notReadyCopy: 'Запустите генератор портфеля, затем перезапустите или обновите локальный demo server.',
          loadingTitle: 'Загрузка радара аккаунтов',
          loadingCopy: 'Читаем сгенерированный артефакт портфеля с локального Vite server.',
        },
      },
      plans: {
        aria: 'Планы доступа',
        statusEyebrow: 'СТАТУС DEMO',
        artifactNotReadyTitle: 'Артефакт не готов',
        artifactNotReadyCopy: 'Запустите генератор плана доступа, затем перезапустите или обновите локальный demo server.',
        loadingTitle: 'Загрузка плана доступа',
        loadingCopy: 'Читаем сгенерированный артефакт с локального Vite server.',
        objectiveEyebrow: 'Цель',
        objectiveTitle: 'Выйти на закупочный комитет через доверенный маршрут внутри правил',
        objectiveCopy:
          'У {{accountName}} есть {{gapCount}} нерешенных пробела в Power Web и {{routeCount}} ранжированных маршрута доступа, созданных {{workflowName}}.',
        rank: 'РАНГ',
        score: 'СКОР',
        recommended: 'Рекомендуется',
        target: 'Цель / {{target}}',
        routeEyebrow: 'Маршрут',
        whyThisRoute: 'Почему этот маршрут',
        expectedStateChange: 'Ожидаемое изменение состояния',
        reviewStatus: 'Статус проверки',
        humanApprovalRequired: 'Требуется подтверждение человека',
        readyForTasking: 'Готово к постановке задачи',
        reviewRule: 'Правило плейбука',
        reviewRuleCopy: 'оставляет этот маршрут review-first.',
        evidence: 'Доказательства',
        boardCoverage: 'Покрытие комитета',
        boardCoverageCopy: 'Видимые и недостающие роли из текущего synthetic account artifact.',
        signalEvidence: 'Доказательства сигналов',
        strength: 'Сила {{score}}',
      },
      planned: {
        workspaceEyebrow: 'ЗАПЛАНИРОВАНО',
        queueEyebrow: 'ЗАПЛАНИРОВАННАЯ ОЧЕРЕДЬ',
        map: {
          title: 'Карта аккаунта',
          description: 'Карта Power Web покажет видимые и недостающие фигуры закупочного комитета вокруг аккаунта.',
          nextSlice: 'Slice 0.5',
        },
        signals: {
          title: 'Сигналы',
          description: 'Лента сигналов покажет источники, свежесть, confidence и governance warnings.',
          nextSlice: 'Slice 0.11',
        },
        playbook: {
          title: 'Плейбук',
          description: 'Плейбук покажет разрешенные маршруты, заблокированные каналы, assets и правила проверки.',
          nextSlice: 'Slice 0.6',
        },
        tasks: {
          title: 'Мои задачи',
          description: 'Подтвержденные маршруты станут кандидатами в задачи после контура human review.',
          nextSlice: 'Slice 0.7',
        },
        inbox: {
          title: 'Входящие сигналы',
          description: 'Новые сигналы будут проходить triage здесь после радарного и source-governance контуров.',
          nextSlice: 'Slice 0.10',
        },
      },
    },
  },
} as const;

function getInitialLocale(): SupportedLocale {
  const stored = window.localStorage.getItem(localeStorageKey);
  return supportedLocales.includes(stored as SupportedLocale) ? (stored as SupportedLocale) : defaultLocale;
}

void i18n.use(initReactI18next).init({
  fallbackLng: defaultLocale,
  interpolation: {
    escapeValue: false,
  },
  lng: getInitialLocale(),
  resources,
});

export { i18n };
